### ISSUE TITLE
超出最大用户后，页面为黑屏状态

### ISSUE THREAD

**Issue by air798** [inveta/PeerStreamEnterprise#19]
当前资源占用满了之后，新加入用户是黑屏状态。可否加一个提示，当前用户已满，联系管理员？或者其它的提示

**Comment by g0415shenw** [comment]
有一个排队事件，参考
https://github.com/inveta/peer-stream/blob/main/README-zh.md

![image](https://github.com/user-attachments/assets/f9f94a0a-43bc-4ffd-b484-d173bd5baca8)

**Comment by 452975214** [comment]
我也遇到了黑屏不显示任何东西的问题，但是我不清楚我这边是否是资源占用满导致的

**Comment by g0415shenw** [comment]
如上监听排队事件，就可以知道资源是占满了。
