### ISSUE TITLE
多服务器上UE路径可能不同但运行的同一个工程

### ISSUE THREAD

**Issue by skypeas** [inveta/PeerStreamEnterprise#23]
使用多服务器负载均衡时，服务器的操作系统、UE路径可能并不相同，但都是同一个工程名、工程标识

**Comment by g0415shenw** [comment]
准备兼容linux和windows双路径，最近会发布这个版本

**Comment by g0415shenw** [comment]
这个已经解决 支持多个路径工程 参考wiki
https://github.com/inveta/PeerStreamEnterprise/wiki/02-%E9%83%A8%E7%BD%B2%E4%BD%BF%E7%94%A8#%E4%B8%8D%E5%90%8C%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%A4%9A%E8%B7%AF%E5%BE%84%E6%94%AF%E6%8C%81
