### ISSUE TITLE
想咨询如何降低视频串流的码率 

### ISSUE THREAD

**Issue by jian19941201** [inveta/PeerStreamEnterprise#31]
现在一个720p的 串流都消耗每秒4M ，带宽压力挺大的

**Comment by g0415shenw** [comment]
最近我们计划把降低码率的参数加上去，稍等一段时间会更新上来。

**Comment by g0415shenw** [comment]
https://github.com/inveta/PeerStreamEnterprise/wiki/02-%E9%83%A8%E7%BD%B2%E4%BD%BF%E7%94%A8#%E9%85%8D%E7%BD%AE%E6%9C%80%E5%A4%A7%E7%A0%81%E7%8E%87
已经支持
