### ISSUE TITLE
咨询问题开启了AudioMixer但使用浏览器访问是没有声音

### ISSUE THREAD

**Issue by gdouyang** [inveta/PeerStreamEnterprise#33]
你好，请我我按教程启动了像素流推送，开启了声音, 全局配置如下，浏览器中没有声音，但在UE播放的电脑中可以听到声音
UE版本: 5.4.3
Chrome版本：131.0.6778.86

有时候能听到声音，但刷新页面后声音就没有了

```
"globlesetting": {
    "WebRTCFps": 30,
    "ResX": "1920",
    "ResY": "1080",
    "Unattended": true,
    "RenderOffScreen": true,
    "AudioMixer": true,
    "WebRTCMaxBitrate": 30
  },
```

**Comment by g0415shenw** [comment]
启用了音频 就不能自动播放视频了，这里有个折中。默认是禁用了音频播放，可以自己增加一个功能 调用打开音频即可。这个是一个video标签。

**Comment by gdouyang** [comment]
问题已解决，在页面上添加一个按钮，点击时执行`ps.audio.play()`即可

**Comment by ou-qx** [comment]
> 问题已解决，在页面上添加一个按钮，点击时执行`ps.audio.play()`即可

你好，我按照你的步骤操作了，还是没有声音，可以指导一下吗

**Comment by gdouyang** [comment]
> > 问题已解决，在页面上添加一个按钮，点击时执行`ps.audio.play()`即可
> 
> 你好，我按照你的步骤操作了，还是没有声音，可以指导一下吗

你这边怎么写的？可以把代码贴出来么

**Comment by ou-qx** [comment]
> > > 问题已解决，在页面上添加一个按钮，点击时执行`ps.audio.play()`即可
> > 
> > 
> > 你好，我按照你的步骤操作了，还是没有声音，可以指导一下吗？
> 
> 你这篇文章怎么写的？可以把代码贴出来么

![image](https://github.com/user-attachments/assets/447946a3-a32b-4a63-9b8e-80788af94f1e)

**Comment by gdouyang** [comment]
> > > > 问题已解决，在页面上添加一个按钮，点击时执行`ps.audio.play()`即可
> > > 
> > > 
> > > 你好，我按照你的步骤操作了，还是没有声音，可以指导一下吗？
> > 
> > 
> > 你这篇文章怎么写的？可以把代码贴出来么
> 
> ![image](https://private-user-images.githubusercontent.com/176638382/394539911-447946a3-a32b-4a63-9b8e-80788af94f1e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4ODQwMjUsIm5iZiI6MTczMzg4MzcyNSwicGF0aCI6Ii8xNzY2MzgzODIvMzk0NTM5OTExLTQ0Nzk0NmEzLWEzMmItNGE2My05YjhlLTgwNzg4YWY5NGYxZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMVQwMjIyMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xODFjYTU3NzM1ZTNjMDQ5YThhOTQwOWJjMGYwYTE1Njg2OTQxODI3YTEwZmU0ZWJmNDc2MWUzMWQ2YmUzM2I5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.tLDkjwFOCE3X2zPXmW2bR6SawI1P6GMCNTLpN4nFvKA)

需要显示的定义一个按钮，点击按钮的时候才执行`ps.audio.play()`，这是浏览器的限定
![image](https://github.com/user-attachments/assets/3af40607-6a4f-45e4-a922-7b69d9f179d6)

**Comment by ou-qx** [comment]
不能在UE播放声音的时候，浏览器也同时播放声音吗，因为我的UE播放声音是不固定的，所以想像官方的像素流一样保持声音传输

**Comment by ou-qx** [comment]
> > > > > 问题已解决，在页面上添加一个按钮，点击时执行`ps.audio.play()`即可
> 需要定义一个按钮，点击按钮的时候才执行`ps.audio.play()`
不能在UE播放声音的时候，浏览器也同时播放声音吗，因为我的UE播放声音是不固定的，所以想像官方的像素流一样保持声音传输

**Comment by gdouyang** [comment]
> 不能在UE播放声音的时候，浏览器也同时播放声音吗，因为我的UE播放声音是不固定的，所以想像官方的像素流一样保持声音传输

浏览器不允许自动播放视频时同时播放声音，官方的像素流能自动播放是因为用户手动点击了播放按钮
